#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#
# Modified by leo.
#

# Source Prezto.

if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Needed for gnome terminal to work.
export TERM=xterm-256color

if [[ "$OSTYPE" == darwin* ]]; then
   # z - jump around
   . `brew --prefix`/etc/profile.d/z.sh

   # do we still need this for tmux on osx? Commenting out for now.
   # export TERM=screen-256color-bce
fi
if [[ "$OSTYPE" == linux* ]]; then
   # z - jump around
   . /usr/lib/z.sh
fi

# Go Language
GODEV=$HOME/code/go # Go std dirs {src, bin, pkg} go here.
G4=$GODEV/src/g4/gopath # Put G4 in a different workspace.
export GOPATH=$GODEV #:$G4 # List all the workspaces.
#export PATH=/usr/local/go/bin:$GODEV/bin:$G4/bin:$PATH # Find the executables.
export PATH=/usr/local/go/bin:$GODEV/bin:$PATH # Find the executables.

# Python
export PYTHONPATH=$HOME/code/python:$PYTHONPATH

# Run local godoc.
alias lgodoc='godoc -http=":6060" -play=true'
alias gopkg='open http://localhost:6060/pkg/?m=flat'

# Go OS-indep bash completion.
x=$(go env | grep GOROOT | gawk -F "\"" '{print $2}') # get GOROOT
if [ -d "$x/misc/bash/go" ]; then
  source $x/misc/bash/go
fi

# Some additional paths.
export PATH=.:$HOME/bin:$HOME/scripts:$HOME/dotfiles/bin:/usr/local/bin:$PATH

# Servers
alias monster="ssh monster -t tmux a"
alias atria="gcloud compute ssh atria --ssh-flag=-AY"

# Debian Backports
alias apti="sudo apt-get -t wheezy-backports install"

### GCLOUD

# Python3 is not supporetd.
export CLOUDSDK_PYTHON="/usr/bin/python2"

# The next line updates PATH for the Google Cloud SDK.
if [[ -d $HOME/google-cloud-sdk ]]; then
    source $HOME/google-cloud-sdk/path.zsh.inc
    source $HOME/google-cloud-sdk/completion.zsh.inc

fi

# GCloud
alias gdisks="gcloud compute disks list --format json | jq '. | .[].name'"
alias snap="gcloud compute disks snapshot"
